const data = {
    products:[
        {
            _id:'1',
            name:'Cream',
            category:'Facial Cream',
            image:'/images/product-1.jpg',
            price:120,
            countInStock: 10,
            brand:'Salvia',
            rating:5,
            numReviews:10,
            description:'high quality cream',
        },
        {
            _id:'2',
            name:'Cream',
            category:'Hand Cream',
            image:'/images/product-2.jpg',
            price:100,
            countInStock: 50,
            brand:'Salvia',
            rating:4,
            numReviews:15,
            description:'high quality hand cream',
        },
        {
            _id:'3',
            name:'Cream',
            category:'Facial Cream',
            image:'/images/product-3.jpg',
            price:50,
            countInStock: 0,
            brand:'Salvia',
            rating:3,
            numReviews:5,
            description:'high quality facial cream',
        },
        {
            _id:'4',
            name:'Oil',
            category:'Body Oil',
            image:'/images/product-4.jpg',
            price:60,
            countInStock: 10,
            brand:'Salvia',
            rating:5,
            numReviews:20,
            description:'high quality oil',
        },
        {
            _id:'5',
            name:'Hand Cream',
            category:'Hand Cream',
            image:'/images/product-5.jpg',
            price:80,
            countInStock: 0,
            brand:'Salvia',
            rating:5,
            numReviews:10,
            description:'high quality cream',
        },
        {
            _id:'6',
            name:'Hand Cream',
            category:'Hand Cream',
            image:'/images/product-6.jpg',
            price:70,
            countInStock: 10,
            brand:'Salvia',
            rating:4,
            numReviews:10,
            description:'high quality cream',
        },
    ]
}

export default data;